export const environment = {
        production: true,
        DEVELOP: {

                APPLICATION: 'ADMIN_PANEL',
                VERSION: 'ng-12',
                Auth_Key: 'eyJhdXRoIjoiOWVkMjMwNzY1ZWU0MmExNGYxNzk0YjY5M2M1MmQ3NzUiLCJESVNUUklCVVRFRF9UT0tFTiI6IjU5ZWMzZDU4NDIxYjdmYzJiOWJkZjBkODU4MmQ2MWI0In0=',
                Froala_Editor_Key: 'qF2F1F2C1rA1C7E6B4E1E4H4E1C10A6eB-11F-11qtpE2fd1pn==',
                WFLOW_API_URL: 'http://bms.memo-tec.com:84/',
                FRONT_END_API_URL: 'https://devapi.admin.farm/service/app/',
                API_URL: 'https://devapi.admin.farm/service/app/adminext/',
                API_URL_OLD: 'https://devapi.admin.farm/service/app/admin/',

                DIGI_API_URL: 'https://devapi.admin.farm/',
                RESOURCE_URL: 'https://consolecdn.admin.farm/',
                RESOURCE_LAMDA_URL: 'https://photo.sw.fit/',
                FIT_IN_200: 'fit-in/200x200/',
                DESIGNBLOCKCSS_URL: 'designedTemplate/designblock.css',
                imageFolders: {
                        PRODUCT_CATEGORY: 'productCategories/',
                        APP_IMAGES: 'app_images/',
                        PRODUCT: 'products/',  PRODUCT_FEED: 'productfeeds/',
                        LANGUAGE_FLAG_URL: 'languages',
                        LOGOS: 'logos/',
                        TICKETS: 'caseAttachment/',
                        IDEAPAGE: 'idpages',
                        FAQ: 'webhelp/',
                        HELPTEMPLATE: 'helpTemplate/',
                        PROMOINFO: 'promotion/',
                        WEB_BACKGROUND: 'web-background/',
                        EMAIL_BACKGROUND: 'emailBackgrounds/',
                        PRODUCT_BADGE: 'productbadge/'
                },
                ADMIN_THEME: 'dark_Theme'

        },
        STAGE: {
                APPLICATION: 'ADMIN_PANEL',
                VERSION: 'ng-12',
                Auth_Key: 'eyJhdXRoIjoiOWVkMjMwNzY1ZWU0MmExNGYxNzk0YjY5M2M1MmQ3NzUiLCJESVNUUklCVVRFRF9UT0tFTiI6IjU5ZWMzZDU4NDIxYjdmYzJiOWJkZjBkODU4MmQ2MWI0In0=',
                Froala_Editor_Key: 'qF2F1F2C1rA1C7E6B4E1E4H4E1C10A6eB-11F-11qtpE2fd1pn==',
                FRONT_END_API_URL: 'https://api.sw.fit/service/app/',
                API_URL: 'https://api.sw.fit/service/app/adminext/',
                API_URL_OLD: 'https://api.sw.fit/service/app/admin/',
                DIGI_API_URL: 'https://api.sw.fit/',
                RESOURCE_URL: 'https://consolecdn.sw.fit/',
                RESOURCE_LAMDA_URL: 'https://photo.sw.fit/',
                FIT_IN_200: 'fit-in/200x200/',
                DESIGNBLOCKCSS_URL: 'designedTemplate/designblock.css',
                imageFolders: {
                        PRODUCT_CATEGORY: 'productCategories/',
                        APP_IMAGES: 'app_images/',
                        PRODUCT: 'products/',
                        LANGUAGE_FLAG_URL: 'languages',
                        LOGOS: 'logos/',  PRODUCT_FEED: 'productfeeds/',
                        TICKETS: 'caseAttachment/',
                        IDEAPAGE: 'idpages',
                        FAQ: 'webhelp/',
                        HELPTEMPLATE: 'helpTemplate/',
                        PROMOINFO: 'promotion/',
                        EMAIL_BACKGROUND: 'emailBackgrounds/',
                        WEB_BACKGROUND: 'web-background/',
                        PRODUCT_BADGE: 'productbadge/'
                },
                ADMIN_THEME: 'dark_Theme'
        },
        LIVEFSC: {
                APPLICATION: 'ADMIN_PANEL',
                VERSION: 'ng-12',
                Auth_Key: 'eyJhdXRoIjoiOWVkMjMwNzY1ZWU0MmExNGYxNzk0YjY5M2M1MmQ3NzUiLCJESVNUUklCVVRFRF9UT0tFTiI6IjU5ZWMzZDU4NDIxYjdmYzJiOWJkZjBkODU4MmQ2MWI0In0=',
                Froala_Editor_Key: 'qF2F1F2C1rA1C7E6B4E1E4H4E1C10A6eB-11F-11qtpE2fd1pn==',
                FRONT_END_API_URL: 'https://masterapi.fotosystem.com/service/app/',
                API_URL: 'https://masterapi.fotosystem.com/service/app/adminext/',
                API_URL_OLD: 'https://masterapi.fotosystem.com/service/app/admin/',
                DIGI_API_URL: 'https://masterapi.fotosystem.com/',
                RESOURCE_URL: 'https://consolecdn.fotosystem.com/',
                DESIGNBLOCKCSS_URL: 'designedTemplate/designblock.css',
                RESOURCE_LAMDA_URL: 'https://photo.fotosystem.com/',
                FIT_IN_200: 'fit-in/200x200/',
                imageFolders: {
                        PRODUCT_CATEGORY: 'productCategories/',
                        APP_IMAGES: 'app_images/',
                        PRODUCT: 'products/',
                        PRODUCT_FEED: 'productfeeds/',
                        LANGUAGE_FLAG_URL: 'languages',
                        LOGOS: 'logos/',
                        TICKETS: 'caseAttachment/',
                        IDEAPAGE: 'idpages',
                        FAQ: 'webhelp/',
                        HELPTEMPLATE: 'helpTemplate/',
                        PROMOINFO: 'promotion/',
                        EMAIL_BACKGROUND: 'emailBackgrounds/',
                        WEB_BACKGROUND: 'web-background/',
                        PRODUCT_BADGE: 'productbadge/'
                },
                ADMIN_THEME: 'dark_Theme'
        },
        LIVEEL: {
                APPLICATION: 'ADMIN_PANEL',
                VERSION: 'ng-12',
                Auth_Key: 'eyJhdXRoIjoiOWVkMjMwNzY1ZWU0MmExNGYxNzk0YjY5M2M1MmQ3NzUiLCJESVNUUklCVVRFRF9UT0tFTiI6IjU5ZWMzZDU4NDIxYjdmYzJiOWJkZjBkODU4MmQ2MWI0In0=',
                Froala_Editor_Key: 'qF2F1F2C1rA1C7E6B4E1E4H4E1C10A6eB-11F-11qtpE2fd1pn==',
                FRONT_END_API_URL: 'https://elapi.sw.fit/service/app/',
                API_URL: 'https://elapi.sw.fit/service/app/adminext/',
                API_URL_OLD: 'https://elapi.sw.fit/service/app/admin/',
                DIGI_API_URL: 'https://elapi.sw.fit/',
                RESOURCE_URL: 'https://res.fotokasten.de/',
                RESOURCE_LAMDA_URL: 'https://photo.fotokasten.de/',
                FIT_IN_200: 'fit-in/200x200/',
                DESIGNBLOCKCSS_URL: 'designedTemplate/designblock.css',
                imageFolders: {
                        PRODUCT_CATEGORY: 'productCategories/',
                        APP_IMAGES: 'app_images/',
                        PRODUCT: 'products/',  PRODUCT_FEED: 'productfeeds/',
                        LANGUAGE_FLAG_URL: 'languages',
                        LOGOS: 'logos/',
                        TICKETS: 'caseAttachment/',
                        IDEAPAGE: 'idpages',
                        FAQ: 'webhelp/',
                        HELPTEMPLATE: 'helpTemplate/',
                        PROMOINFO: 'promotion/',
                        EMAIL_BACKGROUND: 'emailBackgrounds/',
                        WEB_BACKGROUND: 'web-background/',
                        PRODUCT_BADGE: 'productbadge/'
                },
                ADMIN_THEME: 'dark_Theme'

        }


};